[tool.poetry]
name = "py"
version = "0.1.0"
description = ""
authors = ["Nina Blaauw", "Yemeserach Bayu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
